apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psa-car-controller-pvc
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: smb
  volumeName: psa-car-controller-pv
